apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  # Select the Pods that make up this Service.
  selector:
    pod-label: my-backend-pod
  ports:
  - port: 80
    targetPort: 8080
