apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  # If you're using a service such as Google Kubernetes Engine, "LoadBalancer" will generate a public IP address.
  type: LoadBalancer
  # Select the Pods that make up this Service.
  selector:
    pod-label: my-frontend-pod
  ports:
  - port: 80
    targetPort: 8080
